language: r
cache:
  - packages
  - ccache

latex: false

addons:
  apt:
    packages:
       - lmodern
       - texlive-xetex
       - texlive-luatex
       - texlive-generic-recommended
       - texlive-latex-recommended
       - texlive-math-extra
#       - extsizes
#       - lettrine
#       - babel-english
#       - xcolor
#       - pgf
#       - mdframed
#       - zref needspace sttools preprint xifthen ifmtarg colortbl algorithms
#       algorithmicx
#       - changepage
#       - newfloat
#       - fancyhdr
#       - lastpage
#       - titlesc
#       - lineno
#       - footmisc
#       - enumitem
#       - mathdesign
#       - microtype
#       - multirow
#       - wrapfig
#       - pdflscape
#       - tabu
#       - varwidth
#       - threeparttable
#       - threeparttablex
#       - environ
#       - trimspaces
#       - ulem
#       - makecell
#       - epstopdf-pkg

before_install:
  - echo -e "options(Ncpus = 8, repos = structure(c(CRAN = 'https://cloud.r-project.org/')))" > $HOME/.Rprofile
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nCC=ccache gcc -std=gnu99\nCXX=ccache g++\nC11=ccache g++\nC14=ccache g++\nFC=ccache gfortran\nF77=ccache gfortran' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic"); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'remotes::install_local()' # install mlr3book
  - R -q -e 'tic::before_install()'

install:
  - R -q -e 'tic::install()'

script: true

deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true

