language: r
cache:
  - packages
  - ccache
latex: false # didn't work with lualatex out of the box

addons:
  apt:
    packages:
      - lmodern
      - texlive-xetex
      - texlive-luatex
      - texlive-latex-recommended
      - texlive-math-extra

before_install:
  - echo -e "options(Ncpus = 8, repos = structure(c(CRAN = 'https://cloud.r-project.org/')))" > $HOME/.Rprofile
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nCC=ccache gcc -std=gnu99\nCXX=ccache g++\nC11=ccache g++\nC14=ccache g++\nFC=ccache gfortran\nF77=ccache gfortran' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'

install:
  - R -q -e 'tic::install()'

script:
  - R -q -e 'tic::script()'

deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true

jobs:
  include:
    - stage: HTML
      r: release
      env:
        - HTML: true
    - stage: PDF
      pandoc: 2.8.0
      r: release
      env:
        - PDF: true
