language: R
cache: packages
latex: false # didn't work with lualatex out of the box
pandoc: 2.8.0

addons:
  apt:
    packages:
      - lmodern
      - texlive-xetex
      - texlive-luatex
      - texlive-latex-recommended
      - texlive-math-extra

before_install:
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages()'

install:
  - R -q -e 'tic::install()'

script:
  - R -q -e 'tic::script()'
